//  Grammar
//
//  QUERY          ::= "SELECT" SELECT_LIST [ "WITH" WITH_LIST ]
//
//  SELECT_LIST    ::= "(" [ SELECT_ITEM { "," SELECT_ITEM } ] ")"
//
//  SELECT_ITEM    ::= COMPONENT_ACCESS | SELECT_ANYOF_GROUP
//
//  COMPONENT_ACCESS ::= [ "mut" ] COMPONENT_NAME [ "?" ]
//
//  COMPONENT_NAME ::= ["@"](IDENTIFIER | PAIR_COMPONENT)
//
//  PAIR_COMPONENT ::= "(" IDENTIFIER "," IDENTIFIER ")"
//
//  SELECT_ANYOF_GROUP ::= "(" SELECT_ANYOF_ITEM "|" SELECT_ANYOF_ITEM { "|" SELECT_ANYOF_ITEM } ")"
//
//  SELECT_ANYOF_ITEM ::= [ "mut" ] COMPONENT_NAME
//
//  WITH_LIST      ::= "(" [ WITH_ITEM { "," WITH_ITEM } ] ")"
//
//  WITH_ITEM      ::= COMPONENT_NAME | NEGATED_COMPONENT | WITH_ANYOF_GROUP | ROOT_ONLY
//
//  WITH_ANYOF_GROUP ::= "(" COMPONENT_NAME "|" COMPONENT_NAME { "|" COMPONENT_NAME } ")"
//
//  NEGATED_COMPONENT ::= "!" COMPONENT_NAME
//
//  ROOT_ONLY      ::= "-"
//
//  IDENTIFIER     ::= /[A-Za-z_][A-Za-z0-9_]*/
